import React, { Component } from 'react'
import HomeComponent from './Home'
import PreviewArea from './Preview'
import GenreGrid from './Genre'
import SearchComponent from './Search'
import Head from 'next/head'

export default class Routes extends Component {
  render() {
    return (
      <>
        <Head>
          <title>Movie Application</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomeComponent />
      </>
      // <Router>
      //   <div>
      //     <Header />
      //     <Switch>
      //       <Route exact path="/" component={HomeComponent} />
      //       <Route exact path="/info/:type/:id" component={PreviewArea} />
      //       <Route exact path="/genre/:genre/:id" component={GenreGrid} />
      //       <Route exact path="/search/:text" component={SearchComponent} />
      //     </Switch>
      //   </div>
      // </Router>
    )
  }
}
